### ISSUE TITLE
Which function shall I use to get qx? 

### ISSUE THREAD

**Issue by liuyanguu** [sarahertog/ddharmony#12]
I saw an example to get deaths using `DDharmonize_validate_DeathCounts`
Which function shall I use to get qx? 

I once also used an output from `ddharmony` contains all the indicators listed below, but not sure how to obtain it myself: 
![image](https://user-images.githubusercontent.com/11966330/132754833-7b786630-c45c-4ba5-bb6e-bae38568b848.png)

Many thanks for your advice, 
Yang

**Comment by sarahertog** [comment]
Hi Yang Liu,
So far ddharmony only deals with counts of population, births and deaths.  There is not yet any function to extract and validate rates or proportions.  
You can use [https://github.com/timriffe/DDSQLtools] to extract pre-computed life table values from the DemoData database.
Hope this helps!
Sara

**Comment by liuyanguu** [comment]
Many thanks for your quick reply!
